import React, { useState, useEffect, useRef, useCallback, useContext } from 'react';
import './Editor.css';
// ... other imports ...

// ... rest of the component code remains the same ...
// ... existing code ... 